In [5]:
import numpy as np

# Realization of the geometric progression of a matrix in terms of power of its element without numpy.vander method
def power_matrix_without_vander(input_list):
    # vector is realized as an 1d array of input list
    vector = np.array(input_list)
    length = len(input_list)
    print("\nRealization of vander matrix without vander function from left to right is as follows :\n")
    # I have used column_stack to stack the elements of 1d array as columns to get a matrix
    # Reversed(range) is used to get the realization from left to right
    print(np.column_stack([vector**(length-i-1) for i in reversed(range(length))]),"\n")
    # Logic [1,2,3] ie.,for an example take second element which is 2. Hence 2 pow (3-0-1) = 2 pow(2) = 4 and so on..
    print("\nRealization of vander matrix without vander function from right to left is as follows : \n")
    print(np.column_stack([vector**(length-i-1) for i in range(length)]))

power_matrix_without_vander([1,2,3])


def power_matrix_with_vander(input_list):
    vector = np.array(input_list)
    length = len(input_list)
    print("\nRealization of vander matrix with vander function from left to right is as follows :\n")
    print(np.vander(vector,length, increasing = True))
    print("\nRealization of vander matrix with vander function from right to left is as follows : \n")
    print(np.vander(vector,length))
    
power_matrix_with_vander([4,5,6])    


Realization of vander matrix without vander function from left to right is as follows :

[[1 1 1]
 [1 2 4]
 [1 3 9]] 


Realization of vander matrix without vander function from right to left is as follows : 

[[1 1 1]
 [4 2 1]
 [9 3 1]]

Realization of vander matrix with vander function from left to right is as follows :

[[ 1  4 16]
 [ 1  5 25]
 [ 1  6 36]]

Realization of vander matrix with vander function from right to left is as follows : 

[[16  4  1]
 [25  5  1]
 [36  6  1]]
